name: Appium Android Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin

    # Step 3: Set Up Android Environment
    - name: Set Up Android Environment
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget -nc https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip -o commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3" "emulator" "system-images;android-29;google_apis;x86"

    # Step 4: Start Android Emulator
    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: google_apis
        arch: x86
        profile: Nexus 5X
        ram-size: 2048
        disk-size: 6G
        cores: 2
        emulator-options: "-no-window -gpu swiftshader_indirect -no-boot-anim"
        emulator-boot-timeout: 3000

    # Step 5: Wait for Emulator and Disable Animations
    - name: Wait for Emulator and Disable Animations
      run: |
        adb wait-for-device
        for i in $(seq 1 5); do
          adb -s emulator-5554 shell settings put system screen_off_timeout 2147483647 && break
          echo "Retrying screen_off_timeout command... ($i/5)"
          sleep 5
        done
        adb -s emulator-5554 shell settings put global window_animation_scale 0.0
        adb -s emulator-5554 shell settings put global transition_animation_scale 0.0

    # Step 6: Debug: List Files
    - name: Debug:List Files
      run: |
        echo "Listing all files in the workspace:"
        ls -R

    # Step 7: Validate Log Creation
    - name: Validate Log Creation
      run: |
        if [ -f adb-logcat.log ]; then
          echo "ADB log created."
        else
          echo "ADB log not found."
        fi
        if [ -f mvn-output.log ]; then
          echo "Maven output log created."
        else
          echo "Maven output log not found."
        fi

    # Step 8: Handle Missing Logs
    - name: Handle Missing Logs
      run: |
        if [ ! -f adb-logcat.log ]; then
          echo "No ADB logs were generated." > adb-logcat.log
        fi
        if [ ! -f mvn-output.log ]; then
          echo "No Maven logs were generated." > mvn-output.log
        fi

    # Step 9: Run Appium Tests
    - name: Run Appium Tests
      run: |
        mvn clean test -Dtest=newUserFlow.java | tee mvn-output.log

    # Step 10: Capture Logs
    - name: Capture Logs
      run: |
        adb logcat -d > adb-logcat.log || echo "Failed to capture logcat."
        adb shell dumpsys > adb-dumpsys.log || echo "Failed to capture dumpsys."

    # Step 11: Upload Logs
    - name: Upload Logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          adb-logcat.log
          adb-dumpsys.log
          mvn-output.log
        if-no-files-found: warn

    # Step 12: Shutdown Emulator
    - name: Shutdown Emulator
      run: adb emu kill || pkill -f emulator
