name: appium-android

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Use Linux runner

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set Up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    # Step 3: Set Up Android Environment
    - name: Set Up Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

    # Step 4: Install Appium Server
    - name: Install Appium Server
      run: |
        npm install -g appium@1.20.2
        appium -v

    - name: Start Appium Server
      run: |
        nohup appium --log-level debug > appium-server.log 2>&1 &
        echo "Appium Server Initialized"
      shell: bash

    # Step 5: Start Emulator
    - name: Start Emulator
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
        echo "Creating AVD..."
        echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "Nexus 6"
        echo "hw.gpu.mode=swiftshader_indirect" >> $HOME/.android/avd/test.avd/config.ini
        echo "hw.ramSize=2048" >> $HOME/.android/avd/test.avd/config.ini
        emulator -avd test -no-snapshot -gpu swiftshader_indirect -no-boot-anim -accel off -verbose > emulator.log 2>&1 &
        adb wait-for-device
        for i in {1..30}; do
          BOOT_COMPLETED=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
          if [ "$BOOT_COMPLETED" == "1" ]; then
            echo "Emulator is fully booted!"
            adb shell input keyevent 82 # Unlock screen
            break
          else
            echo "Waiting for emulator to boot... ($i/30)"
            sleep 10
          fi
        done
        if [ "$BOOT_COMPLETED" != "1" ]; then
          echo "Emulator failed to boot in time."
          exit 1
        fi

    # Step 6: Debug Logs
    - name: Capture Logs
      run: |
        adb devices
        adb shell getprop > emulator-props.log
        adb logcat -d > emulator-logcat.log
        cat appium-server.log

    # Step 7: Run Tests
    - name: Run Appium Tests
      run: mvn clean test -Dtest=newUserFlow.java

    # Step 8: Upload Logs
    - name: Upload Logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          appium-server.log
          emulator-logcat.log
          emulator-props.log

    # Step 9: Shut Down Emulator
    - name: Shutdown Emulator
      run: adb emu kill || pkill -f emulator
