name: appium-android

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest # Using macOS for hardware acceleration (HAXM)

    strategy:
      matrix:
        api-level: [30] # Specify Google API levels, e.g., [25, 28, 30]
        target: [google_apis] # Use Google APIs as the target for the emulator

    steps:
    # Step 1: Checkout Code
    - uses: actions/checkout@v2

    # Step 2: Set Up Java
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Step 3: Install Appium Server
    - name: Install and Run Appium Server
      run: |
        npm install -g appium@1.20.2
        appium -v
        appium &>/dev/null &

    # Step 4: Start Emulator and Run Tests
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        ram-size: 2048
        disk-size: 6G
        emulator-boot-timeout: 3000
        emulator-options: "-no-snapshot -gpu host -no-boot-anim"
        script: mvn clean test -Dtest=newUserFlow.java
