name: Android Appium Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set Up Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    # Step 3: Install Android SDK
    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "emulator" "cmdline-tools;latest" "system-images;android-30;google_apis;x86_64"

    # Step 4: Create and Start Emulator
    - name: Create and Start Emulator
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
        echo "Creating AVD..."
        echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "Nexus 6"
        echo "hw.gpu.mode=swiftshader_indirect" >> $HOME/.android/avd/test.avd/config.ini
        echo "hw.ramSize=1024" >> $HOME/.android/avd/test.avd/config.ini
        echo "Starting emulator..."
        emulator -avd test -no-snapshot -gpu off -no-boot-anim -accel off -verbose > emulator.log 2>&1 &
        adb wait-for-device
        for i in {1..60}; do
          BOOT_COMPLETED=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
          if [ "$BOOT_COMPLETED" == "1" ]; then
            echo "Emulator is fully booted!"
            adb shell input keyevent 82 # Unlock screen
            break
          else
            echo "Waiting for emulator to boot... ($i/60)"
            sleep 10
          fi
        done
        if [ "$BOOT_COMPLETED" != "1" ]; then
          echo "Emulator failed to boot in time."
          cat emulator.log
          exit 1
        fi

    # Step 5: Install and Start Appium Server
    - name: Install and Start Appium Server
      run: |
        npm install -g appium@1.20.2
        appium -v
        nohup appium --log-level debug > appium-server.log 2>&1 &
        echo "Appium Server Initialized"

    # Step 6: Run Appium Tests
    - name: Run Appium Tests
      run: |
        mvn clean test -Dtest=newUserFlow.java

    # Step 7: Capture Logs
    - name: Capture Logs
      run: |
        cat emulator.log
        adb logcat 
